chatsite/chatapp/urls.py
from django.urls import path
from . import views

app_name = 'chatapp'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='mainpage'),
    path('create/', views.create_room, name='create-room'),
    path('enter/', views.enter_room, name='enter-room'),
    path('<str:room_name>/', views.message_view, name='room'),
    path('delete_chat/<int:room_id>/', views.delete_chat, name='delete_chat'),
]

chatsite/chatsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('chatapp.urls', namespace='chatapp')),
]

chatsite/users/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('add-member/<str:room_name>', views.AddMemberView.as_view(), name='add_member'),
    path('leave_chat/<int:room_id>/', views.leave_chat, name='leave_chat'),

    path('change-password/', views.ChangeUserPassword.as_view(), name='change_user_password'),
    path('change-password/done/', PasswordChangeDoneView.as_view(
        template_name='users/change_password_done.html'), name='change_user_password_done'),


    path('password-reset/', PasswordResetView.as_view(
         template_name='users/password_reset_from.html',
         email_template_name='users/reset_email_form.html',
         success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
         template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete')
]

chatsite/chatapp/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

class RoomModel(models.Model):

    """
    Model representing a chat room.

    This model represents a chat room, including its name, owner, description,
    privacy settings, and the members who have joined it.
    """

    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    room_name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    is_closed = models.BooleanField(default=False)
    members = models.ManyToManyField(get_user_model(), related_name='joined_users')

    def __str__(self) -> str:
        """
        Returns the string representation of the chat room.

        Returns:
            str: The room name.
        """
        return self.room_name
    

class MessagesModel(models.Model):

    """
    Model representing a chat message.

    This model represents a message sent within a chat room, including
    the room name it belongs to, the sender, the message content, and the date/time
    """

    room_name = models.ForeignKey(RoomModel, on_delete=models.CASCADE)
    sender = models.CharField(max_length=255)
    message = models.TextField()
    date_message = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self) -> str:
        """
        Returns the string representation of the chat message.

        Returns:
            str: The room name.
        """
        return str(self.room_name)

chatsite/chatapp/forms.py
from django import forms

from .models import RoomModel

class RoomCreateForm(forms.ModelForm):

    """
    Form class for creating a chat room.

    This form is used to create a new chat room. It includes fields
    for the room name, description, and whether it is private or not.  
    """

    class Meta:
        model = RoomModel
        fields = ['room_name', 'description', 'is_closed']
        labels = {'is_closed': 'Private chat'}
        widgets = {
            'room_name': forms.TextInput(attrs={'class': 'form-control', 'style': "margin: 0; padding: 7px; border: 1px solid #ccc; font-size: 16px;"}),
            'description': forms.Textarea(attrs={'class': 'form-control','cols': 60, 'rows': 1}),
            'is_closed': forms.CheckboxInput(attrs={'class':'form-check-input mt-0'})
        }

    def clean_room_name(self) -> str:

        """
        Custom validation method for the room name.

        Ensures that the room name is unique.
        """

        name = self.cleaned_data['room_name']
        if RoomModel.objects.filter(room_name=name).exists():
            raise forms.ValidationError('This chat already exist')
        return name


class RoomEnterForm(forms.ModelForm):

    """
    Form class for entering a chat room.

    This form is used to enter an existing chat room. It includes
    a field for the room name.
    """

    class Meta:
        model = RoomModel
        fields = ['room_name']

    def clean_room_name(self) -> str:

        """
        Custom validation method for the room name.

        Ensures that the room name corresponds to an existing chat room.
        """

        name = self.cleaned_data['room_name']
        if not RoomModel.objects.filter(room_name=name).exists():
            raise forms.ValidationError('This chat does not exist')
        return name

chatsite/chatapp/views.py
from datetime import timedelta

from django.db.models.query import QuerySet
from django.http import HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.contrib import messages
from django.db import models
from django.http import HttpRequest, HttpResponse

from chatapp.models import MessagesModel, RoomModel
from .forms import RoomCreateForm, RoomEnterForm

# Create your views here.

@login_required
def create_room(request: HttpRequest) -> HttpResponse:

    """
    View to create a new chat room.

    Args:
        request: HttpRequest object.

    Returns:
        HttpResponse: Redirects to the created room or renders the creation form.
    """

    if request.method == 'POST':
        form = RoomCreateForm(request.POST)
        if form.is_valid():
            room = form.save(commit=False)
            room.owner = request.user
            room.save()
            room.members.add(request.user)
            return redirect('chatapp:room', room_name=room.room_name)
    else:
        form = RoomCreateForm()

    return render(request, 'chatapp/index.html', {'form': form, 'title': 'Create Room'})

@login_required
def enter_room(request: HttpRequest) -> HttpResponse:

    """
    View to enter an existing chat room.

    Args:
        request: HttpRequest object.

    Returns:
        HttpResponse: Redirects to the entered room or renders the entering form.
    """

    if request.method == 'POST':
        form = RoomEnterForm(request.POST)
        if form.is_valid():
            room_name = form.cleaned_data['room_name']
            room = RoomModel.objects.get(room_name=room_name)
            room.members.add(request.user)
            return redirect('chatapp:room', room_name=room_name)
    else:
        form = RoomEnterForm()

    return render(request, 'chatapp/index.html', {'form': form, 'title': 'Enter Room'})

@login_required
def delete_chat(request: HttpRequest, room_id: int) -> HttpResponse:

    """
    View to delete a chat room.

    Args:
        request: HttpRequest object.
        room_id: ID of the room to be deleted.

    Returns:
        HttpResponse: Redirects to the main page after deleting the chat room.
    """

    room = get_object_or_404(RoomModel, pk=room_id)
    if request.method == 'POST':
        room.delete()
        messages.success(request, 'Chat deleted successfully.')
        return redirect('chatapp:mainpage')
    else:
        return HttpResponseNotAllowed(['POST'])

@login_required
def message_view(request: HttpRequest, room_name: str) -> HttpResponse:

    """
    View to display messages in a chat room.

    Args:
        request: HttpRequest object.
        room_name: Name of the chat room.

    Returns:
        HttpResponse: Renders the message view template.
    """

    get_room = RoomModel.objects.get(room_name=room_name)
    get_messages = MessagesModel.objects.filter(room_name=get_room)

    if get_room.is_closed:
        if request.user not in get_room.members.all() and request.user != get_room.owner:
            messages.info(request, "You need an invitation to join this chat.")
            return redirect('chatapp:mainpage')
    else:
        if request.user not in get_room.members.all():
            get_room.members.add(request.user)
            messages.info(request, "You have been added to the chat.")

    context =  {
        'room': get_room,
        'room_name': room_name,
        'messages': get_messages,
        'user': request.user,
        'username': request.user.username,
        'current_date': timezone.now(),
        'yesterday': timezone.now() - timedelta(1),
    }

    return render(request, 'chatapp/message.html', context)


class MainPageView(ListView):

    """
    View to display the main page with chat rooms.

    Attributes:
        template_name (str): Template name for rendering the main page.
        context_object_name (str): Name of the variable to be used in the template for the chat rooms.
        paginate_by (int): Number of chat rooms to display per page.
        extra_context (dict): Extra context data to pass to the template.

    Methods:
        get_queryset(self): Retrieve the list of open chat rooms sorted by the number of members.
    """

    template_name = 'chatapp/mainpage.html'
    context_object_name = 'chats'
    paginate_by = 8
    extra_context = {'title': 'Chats'}

    def get_queryset(self) -> models.QuerySet:
        chat_list = RoomModel.objects.filter(is_closed=False).annotate(num_members=models.Count('members')).order_by('-num_members')
        return chat_list

chatsite/chatapp/templates/chatapp/index.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block data %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endblock %}
    <title>Enter Room</title>
</head>

{% block content %}
    <div class="parent">
        <div class="child">
            <h1>{{ title }}</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="hidden" name="text" value="{{ value }}">   
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <center><button type="submit">Submit</button></center><br>
            </form>
        </div>
    </div>
{% endblock %}

</html>

chatsite/chatapp/templates/chatapp/mainpage.html
{% extends 'base.html' %}

{% block content %}
{% if chats %}
    <div class="row">
        {% for chat in chats %}

        <div class="col-md-6 mb-1 w-10 p-3">
            <div class="card">
                {% if chat.is_closed %}
                    <h5 class="card-header" style="background-color: #ebebeb; color: #c90000;">Private Chat</h5>
                {% else %}
                    <h5 class="card-header" style="background-color: #ebebeb; color: #7cc900;">Public Сhat</h5>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ chat.room_name }}</h5>
                    <p class="card-text">{{ chat.description|default:'No description' }}</p>
                    <a href="{% url 'chatapp:room' chat.room_name %}" class="btn btn-primary">Enter the chat</a>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
    
    <nav aria-label="Page navigation example" style="text-align: center;">
        <ul class="pagination" style="list-style: none; display: inline-block; margin: 0; padding: 0; margin-bottom: 20px;">
            {% if page_obj.has_previous %}
            <li class="page-item" style="display: inline-block;">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous" style="text-decoration: none; font-size: 30px;">&laquo;</a>
            </li>
            {% endif %}

            {% for p in paginator.page_range %}
            {% if page_obj.number == p %}
            <li class="page-item active" style="display: inline-block;">
                <span class="page-link" href="?page={{ p }}" style="text-decoration: none; font-size: 30px; color: white;">{{ p }}</span>
            </li>
            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
            <li class="page-item" style="display: inline-block;">
                <a class="page-link" href="?page={{ p }}" style="text-decoration: none; font-size: 30px;">{{ p }}</a>
            </li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item" style="display: inline-block;">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" style="text-decoration: none; font-size: 30px;">&gt;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
{% else %}
    <center><h1>No chats</h1></center>
{% endif %}
    
    

{% endblock %}

chatsite/chatapp/templates/chatapp/message.html
{% extends 'base.html' %}

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Messages</title>
    {% block data %}
    <link rel="stylesheet" href="{% static 'css/message.css' %}">
    <link rel="stylesheet" href="{% static 'css/window.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% endblock %}
</head>

<!-- <body> -->
{% block content %}
    <div class="parent">
        <div class="child-2">
            <center><h2>Chat: {{ room_name }}</h2></center><hr>
            <div style="display: flex; justify-content: space-between;">
                <div>
                    {% if user == room.owner %}
                    <form action="{% url 'users:add_member' room_name=room_name %}" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <!-- Fields for adding users -->
                        <button type="submit" style="background-color: dodgerblue; display: flex; width: 100%;">Add Member</button>
                    </form>
                    </div>
                    <h5 style="margin: 0; text-align: center; flex: 1; width: 100%;">Members: {{ room.members.count }}</h5>
                    <div>

                            <button id="deleteChatBtn" style="background-color: dodgerblue; padding: 10px; color: #000; border: none; border-radius: 5px; width: 120%; margin-left: -20%;"
                            onmouseover="this.style.padding = '10px'; this.style.transition = 'none';"
                            onmouseout="this.style.padding = '10px';">Delete <br> Chat</button>

                        <div id="myModal" class="modal">
                            <div class="modal-content">
                                <span class="close">&times;</span>
                                <p>Are you sure you want to delete this chat?</p>
                                <form id="deleteForm" action="{% url 'chatapp:delete_chat' room_id=room.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit">Yes, delete.</button>
                                </form>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div>
                    {% if user != room.owner %}
                    </div>
                    <h5 style="margin: 0; text-align: center; padding-left: 80px; flex: 1; width: 100%;">Members: {{ room.members.count }}</h5>
                    <div>
                    <form action="{% url 'users:leave_chat' room.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" style="background-color: #659DBD; display: flex; width: 100%;">Leave Chat</button>
                    </form>
                    {% endif %}
                </div>
            </div>
            

        {% if not room.is_closed or user == room.owner or user in room.members.all %}
            <div class="chat-body-parent">
                <div class="chat-body" id="tasks">
                    <div class="message" id="chatContainer">
                      <!-- received messages and displayed here -->
                        {% for i in messages %}
                            {% if i.sender != username %}
                                {% if i.date_message|date:"Y-m-d" == current_date|date:"Y-m-d" %}
                                    <div class="receive">
                                        <p style="color: #000;">
                                            <strong>{{ i.sender }}<span class="small-date"> Today {{ i.date_message|time:"H:i" }}</span> :</strong><br>
                                            {{ i.message }}</p>
                                    </div>
                                {% elif i.date_message|date:"Y-m-d" == yesterday|date:"Y-m-d" %}
                                    <div class="receive">
                                        <p style="color: #000;">
                                            <strong>{{ i.sender }}<span class="small-date"> Yesterday {{ i.date_message|time:"H:i" }}</span> :</strong><br>
                                            {{ i.message }}</p>
                                    </div>
                                {% else %}
                                    <div class="receive">
                                        <p style="color: #000;">
                                            <strong>{{ i.sender }}<span class="small-date"> {{ i.date_message|date:"d.m.Y"}} {{ i.date_message|time:"H:i" }}</span> :</strong><br>
                                            {{ i.message }}</p>
                                    </div>
                                {% endif %}
                            {% else %}
                                <div class="send">
                                    <p style="color: #000;">{{ i.message }}</p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    <!-- end receive messages -->
                    </div>

                    <div class="form">
                        <form action="" id="message-form" method="POST">
                            {% csrf_token %}
                            <textarea id="msg" cols="30" name="message" rows="10" placeholder="Enter your message" required></textarea>
                            <button class="submit" type="submit">Send</button>
                        </form>    
                    </div>
                    {% elif room.is_closed and user != room.owner %}
                        <p>You need an invitation to join this chat.</p>
                    
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
<script>
    function scrollToBottom() {
        var chatContainer = document.getElementById("chatContainer");
        chatContainer.scrollTop = chatContainer.scrollHeight;
    }

    const websocketProtocol = window.location.protocol === "https:" ? "wss" : "ws";
    const wsEndpoint = `${websocketProtocol}://${window.location.host}/ws/notification/{{room_name}}/`;
    const socket = new WebSocket(wsEndpoint);

    document.getElementById('message-form').addEventListener('submit', function(event){
        event.preventDefault();
        const message = document.getElementById('msg').value;
        socket.send(
            JSON.stringify({
                'message': message,
                'room_name': '{{room_name}}',
                'sender': '{{user}}',
            })
        )
    });

    // response from consumer on server
    socket.addEventListener("message", (event) => {
        const messageData = JSON.parse(event.data)['message'];
        console.log(messageData);
        
        var sender = messageData['sender'];
        var message = messageData['message'];

        // empty message input field after message has been sent
        if (sender == '{{ user }}');{
            document.getElementById('msg').value = '';
        }

        // Here's where we append the message to the chatbox.
        var messageDiv = document.querySelector('.message');
        var currentTime = new Date();
        var hours = currentTime.getHours();
        var minutes = currentTime.getMinutes();
        var formattedTime = (hours < 10 ? '0' : '') + hours + ':' + (minutes < 10 ? '0' : '') + minutes;

        if (sender != '{{user}}') { // assuming you have a variable `currentUser` to hold the current user's name
            messageDiv.innerHTML += '<div class="receive"><p style="color: #000;">' + 
                '<strong>' + 
                    sender +
                    '<span class="small-date"> Today '+  formattedTime + '</span>' +
                     ' : <br>' +
                    '</strong>' + 
                    message + 
                    '</p></div>';
        } else {
            messageDiv.innerHTML += '<div class="send"><p style="color: #000;">' + message + '</p></div>';
        }
        scrollToBottom();

    });

    socket.onopen = (event) => {
        console.log("WebSocket connection opened!");
    };

    socket.onclose = (event) => {
        console.log("WebSocket connection closed!");
    };

</script>

<!-- JavaScript to control a modal window -->
<script>
    // Get links to the delete chat button and the modal window
    var deleteChatBtn = document.getElementById("deleteChatBtn");
    var modal = document.getElementById("myModal");
    
    // Get a link to the cross to close the modal window
    var closeBtn = document.getElementsByClassName("close")[0];
    
    // When the user clicks on the "Delete chat" button, we open a modal window
    deleteChatBtn.onclick = function() {
      modal.style.display = "block";
    }
    
    // When the user clicks on the cross (x), we close the modal window
    closeBtn.onclick = function() {
      modal.style.display = "none";
    }
    
    // When the user clicks outside the modal window, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }
</script>
{% endblock %}