chatsite/chatapp/urls.py
from django.urls import path
from . import views

app_name = 'chatapp'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='mainpage'),
    path('create/', views.create_room, name='create-room'),
    path('enter/', views.enter_room, name='enter-room'),
    path('<str:room_name>/', views.message_view, name='room'),
    path('delete_chat/<int:room_id>/', views.delete_chat, name='delete_chat'),
]

chatsite/chatsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('chatapp.urls', namespace='chatapp')),
]

chatsite/users/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('add-member/<str:room_name>', views.AddMemberView.as_view(), name='add_member'),
    path('leave_chat/<int:room_id>/', views.leave_chat, name='leave_chat'),

    path('change-password/', views.ChangeUserPassword.as_view(), name='change_user_password'),
    path('change-password/done/', PasswordChangeDoneView.as_view(
        template_name='users/change_password_done.html'), name='change_user_password_done'),


    path('password-reset/', PasswordResetView.as_view(
         template_name='users/password_reset_from.html',
         email_template_name='users/reset_email_form.html',
         success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
         template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete')
]

chatsite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'chatapp/images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% block data %}
    <!-- Exists and not empty -->
    {% endblock %}
    {% if block.data %}
        <!-- Exists and empty -->
    {% else %}
        <!-- Not Exists -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endif %}

    </head>
    
    <body style="background-color: #aeaeae;">
        <section class="my-navigation">
            <nav class="navbar navbar-expand-lg bg-body-tertiary"  data-bs-theme="dark">
                <div class="container-fluid">
                    <a href="{% url 'chatapp:mainpage' %}" class="navbar-brand" style="margin-right: -250px;">
                        <img src="{% static 'chatapp/images/logo.png' %}" width=25% height=25% alt="logo">
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <div class="navbar-nav me-auto mb-2 mb-lg-0">
                            <a class="nav-link" aria-current="page" href="{% url 'chatapp:enter-room' %}" style="white-space: nowrap; overflow: hidden; margin-right: 10px;">Enter the room</a>
                            <a class="nav-link" href="{% url 'chatapp:create-room' %}" style="white-space: nowrap; overflow: hidden;">Create a room</a>
                        </div>
                        <form class="d-flex justify-content-end" role="search">
                            {% if user.is_authenticated %}
                                <div class="dropdown">
                                    <a href="{% url 'users:profile' %}" class="no-hover-resize btn btn-outline-light me-2" onmouseover="showDropdown()">{{ user.username }}</a>
                                    <div class="dropdown-content" id="dropdownMenu">

                                        <a href="{% url 'users:change_user_password' %}">Change password</a>
                                    </div>
                                </div>
                                    <a href="{% url 'users:logout' %}" class="btn btn-outline-light me-2">Logout</a>
                            {% else %}
                                <a href="{% url 'users:login' %}" class="btn btn-outline-light me-2">Login</a>
                                <a href="{% url 'users:register' %}" class="btn btn-outline-light me-2">Registration</a>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </nav>
            </section>

<section class="content">
{% block content %}
{% endblock %}
</section>

{% block script %}
<script>
// Showing a drop-down menu when you hover over a button
function showDropdown() {
    var dropdownMenu = document.getElementById("dropdownMenu");
    dropdownMenu.classList.add("show");
}

// Hide the drop-down menu when you remove the cursor from the button
function hideDropdown() {
    var dropdownMenu = document.getElementById("dropdownMenu");
    dropdownMenu.classList.remove("show");

    // Close the dropdown menu when clicking outside of it
    var dropdown = document.querySelector('.dropdown');
    if (!dropdown.contains(event.target)) {
        var dropdowns = document.getElementsByClassName("dropdown-content");
        for (var i = 0; i < dropdowns.length; i++) {
            var openDropdown = dropdowns[i];
            if (openDropdown.classList.contains('show')) {
                openDropdown.classList.remove('show');
            }
        }
    }
}

// Adding event handlers to show and hide the dropdown menu
document.querySelector('.no-hover-resize').addEventListener('mouseover', function() {
    showDropdown();
});

document.querySelector('.dropdown').addEventListener('mouseleave', function() {
    hideDropdown();
});

</script>
{% endblock %}

<footer>
    <p>Founder / Owner / CEO - Vladimir Petrov</p>
    <p>&copy; 2024 Partial or complete copying of information from this site for distribution on other resources, including paper, is strictly prohibited.</p>

</footer>

</body>
</html>