chatsite/chatsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('chatapp.urls', namespace='chatapp')),
]

chatsite/users/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('add-member/<str:room_name>', views.AddMemberView.as_view(), name='add_member'),
    path('leave_chat/<int:room_id>/', views.leave_chat, name='leave_chat'),

    path('change-password/', views.ChangeUserPassword.as_view(), name='change_user_password'),
    path('change-password/done/', PasswordChangeDoneView.as_view(
        template_name='users/change_password_done.html'), name='change_user_password_done'),


    path('password-reset/', PasswordResetView.as_view(
         template_name='users/password_reset_from.html',
         email_template_name='users/reset_email_form.html',
         success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
         template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete')
]

chatsite/users/models.py
from django.db import models

# Create your models here.

chatsite/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.forms import PasswordChangeForm

from chatapp.models import RoomModel


class UserLoginForm(AuthenticationForm):

    """
    Form for user login.

    Inherits from Django's AuthenticationForm.

    Attributes:
        model: Model for the user.
        fields: Fields to be displayed in the form.
    """

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')


class RegisterUserForm(UserCreationForm):

    """
    Form for user registration.

    Inherits from Django's UserCreationForm.

    Attributes:
        username: Field for user's login name.
        password1: Field for user's password.
        password2: Field for confirming the password.
        email: Field for user's email.
    """

    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email','password1', 'password2')
        labels = {'email': 'E-mail'}
        widgets = {'email': forms.TextInput(attrs={'class': 'form-input'})}


    def clean_email(self) -> str:

        """
        Clean email field and validate uniqueness.

        Returns:
            str: Cleaned email.
        """

        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('This E-mail already exists!')
        
        return email
    

class AddMemberFrom(forms.Form):

    """
    Form for adding a member to a chat room.

    Attributes:
        user: Field for entering the username of the user to be added.
    """

    user = forms.CharField(label='Username')

    def clean_user(self) -> get_user_model:
        """
        Clean user field and validate existence.

        Returns:
            User: User object.
        """
        username = self.cleaned_data['user']
        User = get_user_model()
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError('User with this username does not exist.')
        
        return User.objects.get(username=username)
    

class ChangePasswordForm(PasswordChangeForm):

    """
    Form for changing user's password.

    Inherits from Django's PasswordChangeForm.

    Attributes:
        old_password: Field for entering the old password.
        new_password1: Field for entering the new password.
        new_password2: Field for confirming the new password.
    """

    old_password = forms.CharField(label='Old password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

chatsite/users/views.py
from typing import Any, Dict
from django import forms
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render

from django.contrib import messages

from django.contrib.auth.views import LoginView
from django.views.generic import CreateView, ListView, FormView
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import get_user_model


from chatapp.models import RoomModel
from users.forms import AddMemberFrom, ChangePasswordForm, RegisterUserForm, UserLoginForm
# Create your views here.


class UserLoginView(LoginView):

    """
    View for user login.

    Inherits from Django's LoginView.

    Attributes:
        form_class: Form class for user login.
        template_name: Template for rendering login page.
        extra_context: Extra context data for rendering template.
        success_url: URL to redirect to after successful login.
    """

    form_class = UserLoginForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Login'}
    success_url = reverse_lazy('chatapp:create-room')


class RegisterUser(CreateView):

    """
    View for user registration.

    Inherits from Django's CreateView

    Attributes:
        form_class: Form class for user registration.
        template_name: Template for rendering registration page.
        extra_context: Extra context data for rendering template.
        success_url: URL to redirect to after successful registration.
    """

    form_class = RegisterUserForm
    template_name = 'users/register_or_login.html'
    extra_context = {'title': 'Registration'}
    success_url = reverse_lazy('users:login')


def logout_user(request: HttpRequest) -> HttpResponseRedirect:
    """
    View for user logout.

    Logs out the user and redirects to login page.

    Args:
        request: HttpRequest object.

    Returns:
        HttpResponseRedirect: Redirects to login page.
    """
    logout(request)
    return redirect('users:login')

def leave_chat(request: HttpRequest, room_id: int) -> HttpResponseRedirect:
    """
    View for leaving a chat room.

    Removes the user from the specified chat room and redirects to main page.

    Args:
        request: HttpRequest object.
        room_id: ID of the chat room.

    Returns:
        HttpResponseRedirect: Redirects to main page.
    """
    room = get_object_or_404(RoomModel, id=room_id)

    if request.user in room.members.all():
        room.members.remove(request.user)

    return redirect('chatapp:mainpage')

class UserProfileView(ListView):

    """
    View for profile.

    Inherits from Django's ListView

    Attributes:
        model: Model for the user.
        template_name: Template for rendering user profile page.
        context_object_name: Name of the variable to use in the template for the list of objects.
        extra_context: Extra context data for rendering template.
        paginate_by: Number of objects to display per page.
    """

    model = get_user_model()
    template_name = 'chatapp/mainpage.html'
    context_object_name = 'chats'
    extra_context = {'title': 'User Profile'}
    paginate_by = 8

    def get_queryset(self) -> QuerySet:
        """
        Get queryset for user profile.

        Returns:
            QuerySet: QuerySet of chat rooms where the user is either owner or member.
        """
        user = self.request.user
        queryset = RoomModel.objects.filter(owner=user) | RoomModel.objects.filter(members=user)
        return queryset.distinct()
    
    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        """
        Get extra context data.

        Adds the current user to the context.

        Args:
            kwargs: Keyword arguments.

        Returns:
            dict: Extra context data.
        """
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


class AddMemberView(LoginRequiredMixin, FormView):

    """
    View for adding a member to a chat room.

    Inherits from Django's LoginRequiredMixin and FormView.

    Attributes:
        form_class: Form class for adding a member.
        template_name: Template for rendering the form.
    """

    form_class = AddMemberFrom
    template_name = 'users/register_or_login.html'


    def form_valid(self, form: forms.Form) -> HttpResponseRedirect:
        """
        Handle form submission.

        Adds the specified user to the chat room if the current user is the owner.

        Args:
            form: Form instance.

        Returns:
            HttpResponseRedirect: Redirect to room page. 
        """
        room_name = self.kwargs['room_name']
        room = RoomModel.objects.get(room_name=room_name)
        
        if room.owner == self.request.user:
            user = form.cleaned_data['user']
            room.members.add(user)
            messages.success(self.request, f'{user.username} added to the chat successfully.')
        else:
            messages.error(self.request, 'Only the owner can add members to the chat.')
        
        return redirect('chatapp:room', room_name=room_name)

    def get_success_url(self) -> forms.Form:
        """
        Get success URL.

        Returns:
            HttpResponseRedirect: Redirect to main page.
        """
        return redirect('chatapp:mainpage')
    




class ChangeUserPassword(PasswordChangeView):

    """
    View for changing user's password.

    Inherits from Django's PasswordChangeView.

    Attributes:
        form_class: Form class for changing password.
        template_name: Template for rendering the form.
        success_url: URL to redirect to after successful password change.
    """

    form_class = ChangePasswordForm
    template_name = 'users/register_or_login.html'
    success_url = reverse_lazy('users:change_user_password_done')
    

chatsite/users/templates/users/change_password_done.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Password changed successfully!</h1>
 
<p >You have successfully changed your password. <a href="{% url 'users:profile' %}">Return to profile.</a></p>
{% endblock %}

chatsite/users/templates/users/login.html
{% extends 'base.html' %}


{% block content %}
    <div class="parent">
        <div class="child">
            <h1>{{ title }}</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="hidden" name="text" value="{{ value }}">   
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <center><button type="submit">Submit</button></center><br>
            </form>
            <hr>
            <p><a href="{% url 'users:password_reset' %}" style="color: #004085;">Forgot your password?</a></p>
        </div>
    </div>
{% endblock %}

chatsite/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

<h1>Password changed</h1>
<p>Congratulations! You have successfully changed your account password. Use it for <a href="{% url 'users:login' %}">login</a>.</p>

{% endblock %}

chatsite/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="parent">
    <div class="child">
        <h1>New password</h1>

        <form method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
            <p><label for="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
            {% endfor %}

            <p><button type="submit">Save</button></p>
        </form>
    </div>
</div>

{% endblock %}

chatsite/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Password reset</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

chatsite/users/templates/users/password_reset_from.html
{% extends 'base.html' %}

{% block content %}
<div class="parent">
    <div class="child">
        <h1>Password recovery</h1>

        <form method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
            <p><label for="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
            {% endfor %}

            <p><button type="submit">Reset by E-mail</button></p>
        </form>
    </div>
</div>

{% endblock %}

chatsite/users/templates/users/register_or_login.html
{% extends 'base.html' %}


{% block content %}
    <div class="parent">
        <div class="child">
            <h1>{{ title }}</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="hidden" name="text" value="{{ value }}">   
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <center><button type="submit">Submit</button></center><br>
            </form>
        </div>
    </div>
{% endblock %}

chatsite/users/templates/users/reset_email_form.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}